### ISSUE TITLE
Blank Screen (White Text no backround)

### ISSUE THREAD

**Issue by LividJava** [unwitting/bleak#10]
This is a Browser issue more than anything Firefox Developer Edition (latest) doesn't pull the backround image up properly so... you can see the issue here right?

![capture](https://cloud.githubusercontent.com/assets/7604544/12367785/00dc0ca2-bbb3-11e5-889f-a1cf035d551b.PNG)

Soo yeah works fine in chrome just not FFDE .-.

**Comment by LividJava** [comment]
Side note its the same way across all ones that use this theme no idea why .-.

**Comment by unwitting** [comment]
Thanks for raising - I've released a patch that gives the `body` a dark background so that for the moment it at least can be read. Working on the problem, since I've reproduced in my own Firefox.

**Comment by LividJava** [comment]
Thanks! I'll Close the issue for now as you are working on it.

**Comment by unwitting** [comment]
Best to keep it open until it's fixed, so we can track what's currently wrong :)

**Comment by unwitting** [comment]
Investigation: Firefox is seeing the inline style on `div.content-wrapper` if you view-source, but for some reason by the time it's parsed everything it's decided to empty that:

<img width="369" alt="screenshot 2016-01-16 09 26 55" src="https://cloud.githubusercontent.com/assets/1509002/12369931/839ef35e-bc33-11e5-8b60-f49b52bf6060.png">

This happens even if I replace the complex style with something basic like `background-color: red`.

**Comment by unwitting** [comment]
Looks to be better :) @Sheefou could you give it a try in your original browser to make sure?

**Comment by LividJava** [comment]
Yep Looks Good :D Thanks!

**Comment by unwitting** [comment]
Awesome 🙃you looking to use the theme? I'd always like to hear about examples of it in use. I can feature on the front page of the theme too.

**Comment by LividJava** [comment]
Im using it for a Personal / Development Blog The Server is hosted in a Docker Container (Just learned how to use it) But i ran in to a bit of a brick wall .-. My Container Takes up my ENTIRE DOMAIN

**Comment by unwitting** [comment]
Are you in Ghost's Slack chatroom? If not, it's the perfect place for getting help with stuff like that - you'll very likely get one of the core team responding to you. https://ghost.org/slack/

Let me know once the blog's live if you decide to go with this theme :)

**Comment by LividJava** [comment]
I am live with this theme :3 http://blog.lividjava.tk (not the most professional Domain Suffix)

**Comment by unwitting** [comment]
Ah! I see what you're saying about the domain now :P

**Comment by LividJava** [comment]
yeah .-.

**Comment by LividJava** [comment]
Probably not a ghost issue and more of a Apache issue
