### ISSUE TITLE
Need help Editing the hbs files!!

### ISSUE THREAD

**Issue by murdoc2211** [unwitting/bleak#11]
Hi, I m a novice developer, and absolutely loved the BLEAK theme for Ghost. I have been working on it to set up a blog for the ecommerce business i currently run. So i need help with a few things, 
The green accents -- can the colour be changed? I want it to match the colour scheme of my ecomm website and thus would like to change the green accents to #7bc4d5. Could you please tell me where and what file should i edit? 

Also, I tried embedding the instagram widget from instansive; i basically copied the embed code and pasted in the <footer id="footer"> in default.hbs, now instead of the footer, the whole main page is an instagram widget! Could you please tell me what i did wrong so that i dont repeat such mistakes?

**Comment by unwitting** [comment]
Hi @murdoc2211 - it looks like you're asking about the _other_ theme for Ghost which also happens to be called bleak :) Confusing, and it's my fault since I came along second, sorry!

I see you've raised an issue on zutrinken/bleak too already, so I'll close this one. Hope you sort your issues!

**Comment by murdoc2211** [comment]
Yeah! I realised that, and i was like shit. So i quickly raised a comment at the right page. 
Thanks for getting back tho!

**Comment by unwitting** [comment]
No worries :D
