### ISSUE TITLE
[object Object] with Twitter

### ISSUE THREAD

**Issue by ghost** [unwitting/bleak#12]
The tweet button provides me with [object Object] prior to proper link & @name
Can't figure out how and/or where to look. Shouldn't it show the blog title instead?

**Comment by unwitting** [comment]
You mean the Tweet button in-post, next to the FB button? Could you give me a concrete example, since it seems to work on unwttng.com?

**Comment by unwitting** [comment]
Nvm, reproduced it. It's due to not having a meta title for the post - I'll fix it up!

**Comment by unwitting** [comment]
@datafluisteraar bleak 0.2.8 fixes this - if you update you should have no more problems :)

**Comment by ghost** [comment]
Great. Added the meta title. Will update bleak later.
