### ISSUE TITLE
Add scrollbar to sidebar if necessary

### ISSUE THREAD

**Issue by THS-on** [unwitting/bleak#15]
Hello,
I really like your theme and use it for my blog but I have one issue that I have a lot links in my sidebar. 
On a normal Display this is not an issue but on small screens because half of the links are not displayed.
Is there a way to fix this other than to add a scrollbar to the sidebar?

Thanks 
THS-on

**Comment by unwitting** [comment]
You're probably best placed to answer that - would you rather see
compressed links or a scrollbar? I'll need to look at how it should be
designed.

**Comment by THS-on** [comment]
I think that a scrollbar is the  best solution. I added the normal scrollbar to the sidebar but then I have formatting problems because the div is also scroll able to x-axis.

**Comment by unwitting** [comment]
What change did you make? Could be that you just need overflow-y?

**Comment by THS-on** [comment]
I think so. I just added `overflow-y: scroll` to the .sidebar but as described before  the div is also scroll able to x-axis. I can fix this with `overflow-x: hidden` but then you cannot the the full length of some long words. 
Maybe a way to fix this is to change to the mobile design if the screen size is to small.
