### ISSUE TITLE
Linkedin sharing URL doesn't match linkedin's pattern

### ISSUE THREAD

**Issue by artiepreston** [unwitting/bleak#18]
Linkedin appear to have a strange way of putting together profile URLs. For example, my profile is: https://www.linkedin.com/in/kate-preston-4b728137 which doesn't match the way bleak puts together urls for this.

Maybe ask the blog user to provide their whole profile url?

**Comment by unwitting** [comment]
You should be able to put `window.__themeCfg.linkedinUsername = 'ktweeden';` in the code injection and get to your profile!
